### ISSUE TITLE
Decision Tree View Error

### ISSUE THREAD

**Issue by OruteZ** [KieranCoppins/Decision-Tree-Package#9]
# Description
After working on and compiling different code, the Decision Tree View no longer opens. This issue requires creating a new Decision Tree each time it occurs.

## Steps to Reproduce
Work on unrelated code.
Compile the code.
Attempt to open the Decision Tree View.
Expected Behavior
The Decision Tree View should open without any issues after compiling other code.

## Actual Behavior
The Decision Tree View fails to open, and the following error message is displayed:
```
Exception thrown while invoking [OnOpenAssetAttribute] method 'KieranCoppins.DecisionTreesEditor.DecisionTreeEditor:OnOpenAsset (int,int)' : NullReferenceException: Object reference not set to an instance of an object
KieranCoppins.DecisionTreesEditor.DecisionTreeView.<PopulateView>b__15_0 (KieranCoppins.DecisionTrees.DecisionTreeEditorNodeBase node) (at Library/PackageCache/com.kierancoppins.decision-trees@e597ef1d9a/Editor/DecisionTreeView.cs:104)
```

## Problem Code
The issue seems to be related to the following code segment:
```Csharp
// Create node views
_tree.Nodes.ForEach(node =>
{
    if (node is DecisionTreeNode)
        CreateNodeView(node as DecisionTreeNode);
    else if (GenericHelpers.GenericHelpers.IsSubClassOfRawGeneric(typeof(Function<>), node.GetType()))
        CreateNodeView(node);
});
```

![image](https://github.com/user-attachments/assets/6b4054b0-57bb-4c5a-8e5e-67b38a9a2541)

**Comment by OruteZ** [comment]
Unity Version is 2021.3.21f

**Comment by KieranCoppins** [comment]
Hi @OruteZ, thank you for creating this issue!

I am unable to reproduce the error you are getting within my own project. Have you created any custom nodes that are in your decision tree? Are you able to share your implementation of them if you have?

What I am guessing from the error, it appears that the tree is holding reference to a null node within your tree and it is erroring trying to load the node view in the decision tree editor. 

I can add some extra validation to this step so that it skips any null nodes, but this means they just won't show and I think it is ideal for this to fail loudly as it is not expected behaviour for a node to be null.

If you are able to share your tree setup, I can try reproduce it my end and see what the deeper issue is!

Many thanks,

Kieran

**Comment by OruteZ** [comment]
https://github.com/OruteZ/Project-H9/tree/main/Assets/Scripts/AI

Here is my custom node code. 
Thank you for your work, and I hope it will help you to resolve this issue.
Thank you.

**Comment by KieranCoppins** [comment]
Hi @OruteZ, I have reviewed your repository and I think I have found the issue.

The issue is with your `EqualVector` node, if you expand the `AI 1` decision tree in the project window, you can see all the nodes within the tree. The `EqualVector` nodes cannot resolve a monobehaviour script for them. I took a look inside your Function scripts and the `EqualVector` node file has been renamed to IsEqual: https://github.com/OruteZ/Project-H9/blob/main/Assets/Scripts/AI/Function/IsEqual.cs

In Unity, the monobehaviour script must be the same name as the class name. If you change the file to be called `EqualVector.cs` or update the class names to be `IsEqual` and then I believe this will resolve your issue! You may have to remake your decision tree again I'm affraid, as the data is now null within that tree object.

Likewise with your `Moveable` node, the script was renamed to `IsMoveable`: https://github.com/OruteZ/Project-H9/blob/main/Assets/Scripts/AI/Function/IsMovable.cs. The class name and file name must match.

I hope this helps and of course let me know if that works for you!
Thank you again for choosing to use my tool!

**Comment by OruteZ** [comment]
I knew what my problem was, thank you for your help!
